### ISSUE TITLE
Suggestion about code style

### ISSUE THREAD

**Issue by ButuzGOL** [mashmatrix/react-lightning-design-system#117]
What do you think if we do default airbnb code style ?
Remove
'jsx-quotes': [2, 'prefer-single'], -> So will be double quote
'react/jsx-curly-spacing': 0, -> So wont do space after { 
Its based on that in own project I do default airbnb style so it makes some inconvenience of switching
I think it relates to all other projects so its better to support default

**Comment by stomita** [comment]
Actually I don't like airbnb style...

**Comment by stomita** [comment]
In our production project the JSX quote style is mostly single quote, curly most include spaces. Actually we put off the checks which have no harm. So I think it is only a matter of preference. We cannot meet all of the preferences.
