### ISSUE TITLE
Integrate in the Design System Starter Kit?

### ISSUE THREAD

**Issue by kaelig** [mashmatrix/react-lightning-design-system#118]
Hi there!

I work in the Salesforce UX team, and I am the creator the the [Lightning Design System Starter Kit](https://github.com/salesforce-ux/design-system-starter-kit) and one of our designers has just started a [react branch](https://github.com/salesforce-ux/design-system-starter-kit/tree/react) in which he put some boilerplate code to prototype using JSX.

I was wondering if that was something that'd be of interest to you. If so, feel free to contribute to that branch or to fork the starter kit and make your own version of it!

PS: thanks for your work on react-lightning-design-system, it's great to see such good stuff emerging from the community.

**Comment by ButuzGOL** [comment]
Thanks for invitation 
Lightning Design System Starter Kit cool idea and I think react components will simplify the building
Also your designers can components from this repo it has quite big amount of it

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
