### ISSUE TITLE
Select in a Datepicker doesn't show years in Firefox

### ISSUE THREAD

**Issue by rafaljanicki** [mashmatrix/react-lightning-design-system#125]
Firefox: v50
Screenshot: https://i.imgur.com/Lw1RBqB.png

In Firefox years in a Datepicker module are not shown, works in Chrome & IE. This is most probably because Select is wrongly rendered - the value should be provided inside <option>, not as an argument

Current: <option label="2011" value="2011"></option>
Should be: <option label="2011">2011</option>

**Comment by stomita** [comment]
This is due to the former commits including datepicker component spec change. The previous version (1.3.4) doesn't have this.
@ButuzGOL your commit a6a8500 has changed the datepicker year selection component from Picklist to Select. Is there any issues around this ?

**Comment by stomita** [comment]
#138 is the issue also raised by changing from Picklist to Select.

**Comment by ButuzGOL** [comment]
Yes it was part of slds2 changes
https://www.lightningdesignsystem.com/components/datepickers/

**Comment by rafaljanicki** [comment]
Hey @stomita ,

Did you have a chance to look into this bug?

**Comment by bondz** [comment]
This should be fixed now with #195 merged.
