### ISSUE TITLE
Lookup search box is not appearing after an item is selected 

### ISSUE THREAD

**Issue by stomita** [mashmatrix/react-lightning-design-system#131]
Lookup (controlled) example is not working correctly from ver 1.3.0.
When an item is selected, the selection search box is not rendered even clicking the pill's close button.

![](https://i.gyazo.com/3c478c3f112d36b759511e928486600d.gif)

Expected behavior (screencast taken in 1.2.1)

![](https://i.gyazo.com/79f4e4754b20bc45f458c00edaaab397.gif)

**Comment by bondz** [comment]
@stomita It doesn't work now. Should a new issue be opened?

**Comment by stomita** [comment]
@bonz yes please if you face the problem
