### ISSUE TITLE
Picklist selectedText prop should have default value or not

### ISSUE THREAD

**Issue by stomita** [mashmatrix/react-lightning-design-system#146]
@gkoychev The PR #136 is a support of multiselect picklist, which is neat and has successfully been merged. Unfortunately after the merge I noticed that the default `selectedText` property was set , and the default message is rendered in every not-selected picklists even in Japanese environment. We happened to add i18n text for these components.
So it comes to a question about the need of defaulting this message text. IMO developers want them to be empty or customize by themselves when it is surely required. It can also be said that setting a english text as default may against to language neutrality. How do you think about this ?

**Comment by gkoychev** [comment]
Hi @stomita, I think it could be removed
but also you could pass correct translation to that property

**Comment by stomita** [comment]
@gkoychev It would be good to keep the translation tasks to developers and continue not including the i18n feature in the lib.
