### ISSUE TITLE
Move scripts in examples => stories

### ISSUE THREAD

**Issue by stomita** [mashmatrix/react-lightning-design-system#162]
Currently examples are used for assuring changes will not bring regression visually. For this usage the storybook will be used and storybook hub is easiest way to provide the reviewing PR. Moving these code to storybook is the immediate issue in order to off-load the accepting the incoming PR without bringing regressions.

**Comment by ButuzGOL** [comment]
👍

**Comment by ButuzGOL** [comment]
https://github.com/storybooks/storyshots

**Comment by stomita** [comment]
@ButuzGOL Good. This might help the initial checking of degradation.
