### ISSUE TITLE
Keeping clean the master with additional features

### ISSUE THREAD

**Issue by stomita** [mashmatrix/react-lightning-design-system#164]
@ButuzGOL The recently merged PRs includes features 
which I would like to be introduced more managed way. 

As the lib is related to the user interface and look and feels 
we need to check the behavior manually
which cannot be done in automatic test.
 
Additionally I'm currently coping with the enhancement while accepting
 PRs which are with plenty of regressions. 
The pollution of the code in master really impacting our production code releases.
So could you please refrain the unnecessary feature merging 
before I prepare the storybook environment which describes the expected behavior ?

**Comment by stomita** [comment]
@ButuzGOL the #137 is the issue of introducing storybooks and it will replace current examples in #162. The future PR we accept should be checked here and features should include the stories in here, not in examples

**Comment by ButuzGOL** [comment]
ok but those pr was 10 days ago so please also add comments
i am usually wait for comments but if no from my side was everything ok
and i think we shouldn't ignore our contributors for long time

**Comment by stomita** [comment]
To streamline the PR checking requires storybook and PR based checking environment like storybook hub. It seems 10 days abscense is not quite long in our side as we have several public and private events which would prevent from accessing code.

**Comment by stomita** [comment]
Considering #170 the release will be much controllable
