### ISSUE TITLE
DateInput does not fire onChange event. 

### ISSUE THREAD

**Issue by bondz** [mashmatrix/react-lightning-design-system#167]
DateInput does not call the onChange event handler when specified.

**Comment by stomita** [comment]
@bondz Currently the `onChange` event occurs `Input`, `Textarea` components which have the corresponding react elements (`<input>`, `<textarea>`), not the combined ones. Use `onValueChange` instead.

**Comment by bondz** [comment]
Thanks @stomita, value changed works. I was trying to use a catch all function setting state with `e.target.name` and `e.target.value`.
