### ISSUE TITLE
Master merging

### ISSUE THREAD

**Issue by stomita** [mashmatrix/react-lightning-design-system#170]
@ButuzGOL 
The master is the source of the npm registry, I'm very having difficulty of version controlling using semver and facing troubles for just patching the bugs of current code as the PRed new features are already merged. I don't want to create hotfix branches and cherry-pick them as much as possible.
Instead of merging PR directly to the master, I propose using `development` branches which are ready to be merged to master when the minor update is possible.

**Comment by ButuzGOL** [comment]
i am ok with this

**Comment by stomita** [comment]
OK, thanks
