### ISSUE TITLE
Picklist and PickListItem selected item

### ISSUE THREAD

**Issue by bondz** [mashmatrix/react-lightning-design-system#172]
Given
```jsx
<Picklist name="sample" label="Sample" menuSize="medium">
     <PicklistItem selected value="open" label="Open" />
     <PicklistItem value="completed" label="Completed" />
</Picklist>
```

when the Component renders, the Item with value `open` should be selected by default.

Currently, using `selectedText` on the Picklist works, but the `PickListItem` is not checked. Using the `value` prop of the PickList works and checks the Item but the value can no longer be changed; this behaviour can be verified in [here: stories](https://d190dde4-a398-4a9f-926a-cf22c04425f3.sbook.io/?knob-opened=undefined&knob-loading=undefined&knob-disabled=undefined&knob-iconAlign=left&knob-required=undefined&knob-disabled%20%231=undefined&knob-disabled%20%232=undefined&knob-label=Picklist%20Label&knob-disabled%20%233=undefined&knob-multiSelect=undefined&selectedKind=Picklist&selectedStory=Single%20item%20selected&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

**Comment by stomita** [comment]
> Using the value prop of the PickList works and checks the Item but the value can no longer be changed; 
The correct usage for the uncontrolled picklist is not using `value` but `defaultValue` property.
```jsx
<Picklist name="sample" label="Sample" menuSize="medium" defaultValue="open">
     <PicklistItem value="open" label="Open" />
     <PicklistItem value="completed" label="Completed" />
</Picklist>
```

**Comment by bondz** [comment]
@stomita thank you. Still getting used to the react way of doing things, I was trying to do that for a controlled component, sorry.
