### ISSUE TITLE
Import of items causes exception in Salesforce Lightning App with locker service

### ISSUE THREAD

**Issue by florian-interaktiv** [mashmatrix/react-lightning-design-system#186]
Hey there,

I'm currently trying to build react applications running as a lightning component in Salesforce Lightning.
As with Spring'17 the locker service will be deployed I've enabled locker service in my SF dev org.

I've kickstarted a react webkit app using [https://github.com/react-webpack-generators/generator-react-webpack](https://github.com/react-webpack-generators/generator-react-webpack) and installed 
react-lightning-design-system via npm.

Right now, the test app containing the lightning component runs without any errors in SF.
But after I imported some react lightning elements into my react component I'm getting the following error (Firefox 51.0.1 32bit) 

`TypeError: Argument 1 of Crypto.getRandomValues does not implement interface ArrayBufferView. throws at https://fgsandbox-dev-ed.lightning.force.com/auraFW/javascript/uUttwQR-pk5rKvOBHB6bAQ/aura_prod.js:590:207`

Chrome (56.0.2924.87):
`Uncaught TypeError: Failed to execute 'getRandomValues' on 'Crypto': parameter 1 is not of type 'ArrayBufferView'.
throws at https://fgsandbox-dev-ed.lightning.force.com/auraFW/javascript/uUttwQR-pk5rKvOBHB6bAQ/aura_prod.js:590:212`

This is my react component:

`
import React from 'react';
import './app.scss';

import { Tabs, Tab, Icon, MenuItem } from 'react-lightning-design-system';

class AppComponent extends React.Component {

  render() {
    return (
      &lt;div className="index"&gt;
          &lt;h1&gt;Hallo&lt;/h1&gt;
          &lt;Tabs type='default' defaultActiveKey='1'&gt;
              &lt;Tab eventKey='1' title='Tab 1'&gt;This is in tab #1&lt;/Tab&gt;
              &lt;Tab eventKey='2' title='Tab 2'&gt;This is in tab #2&lt;/Tab&gt;
              &lt;Tab eventKey='3' title='Tab 3'&gt;This is in tab #3&lt;/Tab&gt;
          &lt;/Tabs&gt;
      &lt;/div&gt;
    );
  }
}

AppComponent.defaultProps = {
};

export default AppComponent;
`

This code works in my local environment.

Anyone who has probably experienced the same errors?

Thanks!

**Comment by stomita** [comment]
I don't know why it occurs. Actually the LockerService doesn't have compatibility for many modules in npm. When your app or internally depending modules are using one of them, it will raise error.

It seems the error comes from crypto module. how about shimming the module like https://mixmax.com/blog/requiring-node-builtins-with-webpack

**Comment by florian-interaktiv** [comment]
Thanks for your answer.
I tried your suggestion but it didn't help,

I think that the error is based on the Uint8Array .
Somehow LockerService  modifies it (or the window object) (however) so it doesn't implement ArrayBufferView interface.
The function crypto.getRandomValues() expects such an object implementing this interface and throws an error if not.

I will switch to SF developer forum.

Thanks :)

Btw.: is this lib compatible to locker service?

**Comment by john-benson** [comment]
The issue appears to be that the LockerService is prohibiting the use of WHATWG crypto-based RNG to generate UUIDs in "production" mode.

Not entirely sure what the remedy here is other then NOT generating UUIDs.

**Comment by stomita** [comment]
The UUID in react-lds is only used to create non-conflicting element id in the page thus the crypto based strong random might not be mandatory. I'll consider if it can be replaced.

**Comment by john-benson** [comment]
No worries; honestly its on SF to provide a functional JS environment. There's no reason getRandomNumbers SHOULDN'T work for security reasons.

Thanks for the hard work.

**Comment by florian-interaktiv** [comment]
@john-benson Thanks for your explanation of UUID generation.
In deed they need to fix it.
Any ideas where I can report this problem?

**Comment by john-benson** [comment]
@florian-interaktiv Other then their support forms; if you have an actual support contract with them you could communicate the issue to your rep.

It's something they'll have to fix on their end and not something you can fix. For now, if you really need RLDS I'd recommend forking and removing the random ids.

**Comment by florian-interaktiv** [comment]
@john-benson Thanks :)
I'm going to open a support ticket, the dev forum's answers were not really helpful ([https://developer.salesforce.com/forums/ForumsMain?id=9060G000000I6HHQA0](https://developer.salesforce.com/forums/ForumsMain?id=9060G000000I6HHQA0) )

**Comment by john-benson** [comment]
No problem; just make sure you specify that its in the context of the "evalAndReturn" function which handles the imported JS files.

Based on my understanding, the Crypto lib would still work in "normal" lightning mode but w/e fuckery their doing with imported scripts seems to break stuff.

@stomita You can probably close this ticket as this is almost certainly an issue with LockerService and not react-lightning-design-system
