### ISSUE TITLE
Icons are not showing

### ISSUE THREAD

**Issue by Lc0rE** [mashmatrix/react-lightning-design-system#217]
This is more an odd question than an issue, but as a developer with poor experience in React, I'm asking this. I also hope it will be useful to other young developers struggling for an answer on StackOverflow.

By the way, I'm importing the components in a new project (bootstrapped with FB's create-react-app) and I can't figure out how to show icons:

```javascript
import React, { Component } from 'react';
import { Button } from '../node_modules/react-lightning-design-system';
import { Icon } from '../node_modules/react-lightning-design-system';
import '../node_modules/@salesforce-ux/design-system/assets/styles/salesforce-lightning-design-system.css'


class App extends Component {
render() {
    return (
      <div className="App">
          <Button type='neutral'>Neutral</Button>
          <Button type='neutral' disabled>Disabled Neutral</Button>
          <Button type="icon-border" icon="settings"/>
      </div>
    );
  }
}

export default App;
```
Result:
![screenshot 2017-05-17 16 40 00](https://cloud.githubusercontent.com/assets/7023628/26159702/96ce2afa-3b1f-11e7-8e45-67fed9b719b0.png)

What am I missing?

**Comment by ButuzGOL** [comment]
you need to add 
```
import { util } from 'react-lightning-design-system';
util.setAssetRoot(path to assets);
```

**Comment by Lc0rE** [comment]
Thanks for your answer. 
"path to assets" stays for?

**Comment by ButuzGOL** [comment]
you should be sure that your asset path is available from server

usually its
dist/
--public
----assets
--index.html
--bundle.js
util.setAssetRoot('./public/assets');

**Comment by Lc0rE** [comment]
Thanks again for the answer. I'm still not getting the point. Which asset are we talking about?
My project asset? react-lightning-design-system asset? #salesdorce-ux/lightning-design-system asset?
Maybe I have not a clear idea of what an asset is.. please be patient :)

**Comment by Lc0rE** [comment]
I did just try to puth the asset `util.setAssetRoot('./bower_components/salesforce-lightning-design-system/assets');` (installed with bower) and all is working fine. Thanks!

**Comment by streco** [comment]
My application is being used within a visualforce page - which means I was able to to do:

import { util } from 'react-lightning-design-system';
util.setAssetRoot('/apexpages/slds/latest/assets');
