### ISSUE TITLE
TextArea onChange handler

### ISSUE THREAD

**Issue by anoopnair** [mashmatrix/react-lightning-design-system#219]
Hello -

     I have a simple (controlled) TextArea with an onChange handler. In the onChange(event, value) method, value seems to always be return as undefined.

     Interestingly, in the React Storybook example of TextArea as well, I see the event, but not the value.

     Any ideas? 

Thanks.

**Comment by stomita** [comment]
Basically `onChange` event simply delegate to its containing react elements (`<textarea>`), so the first argument `e` becomes SyntheticEvent. If you want to get the value of the element, use `e.target.value`.

**Comment by anoopnair** [comment]
Thanks a bunch, @stomita .
