### ISSUE TITLE
Checkbox can't be changed when checked prop is set

### ISSUE THREAD

**Issue by emontalbano** [mashmatrix/react-lightning-design-system#241]
On the demo page as well as live, if a checkbox has the checked prop set to any value it cannot be modified. On the demo page the only checkboxes that work are the ones which don't use the checked prop (ex. <Checkbox /> vs <Checkbox checked={checked} />).

**Comment by stomita** [comment]
Use `defaultChecked` if you want to uncontrolled behavior. When you set `checked` property all behavior is controlled by the component container who pass the property.
