### ISSUE TITLE
Table js PropType

### ISSUE THREAD

**Issue by rbx44** [mashmatrix/react-lightning-design-system#252]
Table.js is using React.PropType.

 ![image](https://user-images.githubusercontent.com/8643739/33140955-357b9962-cf77-11e7-854f-6632dec453d2.png)

**Comment by rbx44** [comment]
DateInput: Console Logs

**Comment by rbx44** [comment]
![image](https://user-images.githubusercontent.com/8643739/33141777-d1385a6e-cf79-11e7-8c7a-f993500e265d.png)

**Comment by tarot** [comment]
in [stories/GridStories.js#L16](https://github.com/mashmatrix/react-lightning-design-system/blob/6e1f587b5492faa233f537937ba08a132bde3d66/stories/GridStories.js#L16) as well

**Comment by stomita** [comment]
#261 fixes this
