### ISSUE TITLE
Lookup rendering in 2.5.4

### ISSUE THREAD

**Issue by rbx44** [mashmatrix/react-lightning-design-system#271]
I upgraded to 2.5.4 and for some reason Lookup component is rendering inside another react portal component and not the component I want it to be. 
.slds-lookup -- at the bottom of the page. 
![image](https://user-images.githubusercontent.com/8643739/34174594-20c05d3e-e4bf-11e7-84da-4e0f5d84b63c.png)

Can you please take a look at it asap? Thanks!

**Comment by stomita** [comment]
@rbx44 do you have any issue on this ? the portal element is not used anywhere other than the dropdown. 
It is required to add slds-lookup to list menus to correctly rendered in the portal element.
