### ISSUE TITLE
picklist rendering 2.5.4 / React 16.2

### ISSUE THREAD

**Issue by miloandmilk** [mashmatrix/react-lightning-design-system#273]
![image](https://user-images.githubusercontent.com/4624639/34384826-9f8b83fc-eb16-11e7-8047-815d66c339ed.png)

After upgrading to 2.5.4 and react 16.2 picklists and lookup items are not rendering properly.

**Comment by stomita** [comment]
Seems SLDS styles are not applied correctly.
Which version of SLDS are you using ?

**Comment by miloandmilk** [comment]
I am using the version picked up within a visualforce page on API version 41. 

I am using the code util.setAssetRoot('/apexpages/slds/latest/assets/'); to set the path.

Version 2.4.0 works fine with picklists and lookups with exactly the same code.

**Comment by rbx44** [comment]
I am having the same issue. #271 
All components used to render fine till 2.4.5. DateInput field width is also inconsistent

**Comment by stomita** [comment]
It seems in SLDS in VF without SLDS namespace class name have the problem. Currently the `slds-scope` class should be applied to document.body, or wrapping root element with `<ComponentSettings portalClassName="slds-scope">` will solve this.
