### ISSUE TITLE
React 15 - CheckboxGroup has been broken 

### ISSUE THREAD

**Issue by john-benson** [mashmatrix/react-lightning-design-system#61]
React 15 had competently removed the use of "ref".

This completely breaks the CheckboxGroup component. I have a change in my fork that fixes this but requires that the user pass down the list of values to the CheckboxGroup.

Is this a PR this project would be interested in? Or would you prefer another approach

**Comment by ButuzGOL** [comment]
pull request #60

**Comment by ButuzGOL** [comment]
I think it can be close when we will update React with this https://github.com/facebook/react/issues/6779 fix
