### ISSUE TITLE
Support SLDS 2.0

### ISSUE THREAD

**Issue by stomita** [mashmatrix/react-lightning-design-system#70]
If you interested in this, please write down a issue/comment when you surface any UI rendering corruption in SLDS 2.0.

SLDS release note (some breaking change information is included)
http://www.lightningdesignsystem.com/release-notes/

**Comment by stomita** [comment]
PR #68 reports the problem of lookup component.

**Comment by ButuzGOL** [comment]
I apply as a test and seems like some small bugs appear but nothing big so hope I or somebody will push pr
