### ISSUE TITLE
Transfering repository ownership

### ISSUE THREAD

**Issue by stomita** [mashmatrix/react-lightning-design-system#74]
To clarify that `react-lightning-design-system` is actually from the project of my company [Mashmatrix](https://github.com/mashmatrix) development, I would like to transfer this personal repository to the organization's control.

I think this will not have effect almost all of you - except the repository URL becomes different. The license will not change, still provided in MIT. We may put a contributor's agreement to be legally clear.

**Comment by marcban** [comment]
Hello @stomita, 
Could you also include the source repository url in package.json and republish a new version on npm? It is necessary to use it as a [Webjar](http://www.webjars.org/).

Something like (change the url to the new one) :

`"repository" :
  { "type" : "git"
  , "url" : "https://github.com/stomita/react-lightning-design-system.git"
  }`

I really like your project !

**Comment by stomita** [comment]
@marcban will include in next npm publish

**Comment by stomita** [comment]
Moved to new repository. Please change your remote repository url to new one.
