### ISSUE TITLE
Add  @salesforce-ux/design-system as a dependency

### ISSUE THREAD

**Issue by BLamy** [mashmatrix/react-lightning-design-system#84]
Currently, you need to install it separately if you want styling.

**Comment by stomita** [comment]
The design system file can be referenced from static resources, bower, or other external providers. It is not always comes with the build.

**Comment by BLamy** [comment]
You should probably document that then. 

Right now there is absolutely nothing telling people using this library that they need to go out and get this additional dependency. It takes a bit of digging through examples to figure what you need to get and how to get it.
