### ISSUE TITLE
Datepicker minDate/maxDate is not render disabled/enabled date correctly

### ISSUE THREAD

**Issue by stomita** [mashmatrix/react-lightning-design-system#97]
@snownoop The feature you added in previous PR #95 - adding property to set minDate / maxDate to date picker -  is not working as anticipated. In the datepicker example "Datepicker min date", *disabled* and *enabled* days are not shown what we expected. Following is the calendar of Aug 2016 where minDate is set to "2016-07-10".

<img width="288" alt="localhost_3000___datepicker" src="https://cloud.githubusercontent.com/assets/23387/17961043/73f8460c-6ae4-11e6-87c7-d388e6f8afa7.png">

**Comment by snownoop** [comment]
@stomita ok let me check it. Will try to fix that. Thanks.

**Comment by ButuzGOL** [comment]
Fix in #105 commit 5ffefb7
